---
- name: Check AWS CLI is installed
  ansible.builtin.raw: which aws
  check_mode: false
  changed_when: false
  failed_when: is_aws_installed.rc > 1 # control when the task fails
  register: is_aws_installed

- name: Is AWS CLI installed?
  ansible.builtin.debug:
    var: is_aws_installed
  tags: debug

- name: Download the awscli bundle.
  get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
  register: aws_cli_download_bundle
  when: is_aws_installed.rc != 0

- name: Result of downloading the awscli bundle.
  ansible.builtin.debug:
    var: aws_cli_download_bundle
  when: is_aws_installed.rc != 0
  tags: debug

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no
  register: aws_cli_unarchive_installer
  when: is_aws_installed.rc != 0 and aws_cli_download_bundle.failed == false

- name: Result of unarchiving the installer.
  ansible.builtin.debug:
    var: aws_cli_unarchive_installer
  when: is_aws_installed.rc != 0 and aws_cli_download_bundle.failed == false
  tags: debug

# May fail if python3 and python-env
# apt install python3.8-venv python3.8
- name: Install awscli package.
  shell: sudo /tmp/awscli-bundle/install
  when: is_aws_installed.rc != 0 and aws_cli_unarchive_installer.failed == false
