---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    # List all the directories from the roles directory
    - name: Find roles
      ansible.builtin.command: ls ./roles # ls $HOME/.dotfiles/roles
      register: roles_dir
      ignore_errors: true
      changed_when: false
      tags:
        - always

    - name: Display roles directories
      ansible.builtin.debug:
        var: roles_dir.stdout_lines
      tags:
        - debug

    # By default or all tag, use map roles from the roles directories. If tags are define, just use defined tags.
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or roles_dir.stdout_lines }}"
      tags:
        - always

    - name: Roles to be launch
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
