#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"

cd $script_dir
scripts=$(find runs -maxdepth 2 -mindepth 1 -type f -type f \( -perm -u=x -o -perm -g=x -o -perm -o=x \))

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

if [[ -z "$scripts" ]]; then
    log "No scripts found"
    exit 1
fi

if [[ -z "$filter" ]]; then
    log "Running all scripts"
else
    log "Filter provided: $filter"
fi

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        # Only show the filters with the dry run flag
        if [[ $dry == "1" ]]; then
            log "filtered: $filter -- $script"
        fi
        continue
    fi
    log "running script: $script"
    execute ./$script
done
