---
- name: Install fnm
  community.general.homebrew:
    name: fnm
    state: present
  
- name: Copying .npmrc config
  copy:
    src: config/ # Only copy the files of the folder and not the folder
    dest: "{{ ansible_user_dir }}"
    mode: 0644
    force: true

- name: Install latest node version using fnm
  shell: >
    fnm install --lts
