---
- name: Install karabiner-elements
  community.general.homebrew:
    name: karabiner-elements
    state: present
- name: Check if .config/karabiner dir exist, and create if not
  file: 
    path: "{{ ansible_user_dir }}/.config/karabiner/"
    state: directory
- name: Copying karabiner config
  copy:
    src: config/karabiner.json
    dest: "{{ ansible_user_dir }}/.config/karabiner/karabiner.json"
    mode: 0644
    force: true