#!/usr/bin/env bash

# Install bat for macos
if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install bat
    cd runs/bat
fi

# Install bat for linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get install bat
fi


mkdir -p $HOME/.config/bat
cp ./config $HOME/.config/bat/config

# Rename package from batcat to bat only for ubuntu linux
# https://github.com/sharkdp/bat?tab=readme-ov-file#on-ubuntu-using-apt
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ln -s /usr/bin/batcat $HOME/.local/bin/bat
fi
bat cache --build