#!/usr/bin/env bash

# Install tmux for macos
if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install tmux
fi

# Install tmux for linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get install tmux
fi

cd runs/tmux
cp ./.tmux.conf $HOME/.tmux.conf
echo "tmux installed! Remember -> Press Prefix + I to install plugins!"