#!/usr/bin/env bash


if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install go
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Get last version
    go_lastest_version=$(curl -s https://go.dev/VERSION\?m\=text | head -n 1)

    # Check if go is installed.
    # If it is installed, check if it is the latest version.
    if ! command -v go &> /dev/null; then
        echo "Go is not installed"
    else
        current_go_version=$(go version | awk '{print $3}')
        echo "Go installed version: $current_go_version"
        if [[ "$current_go_version" == "$go_lastest_version" ]]; then
            echo "You are already using the latest version of Go"
            return
        fi
    fi

    # Download the latest version of Go
    go_download_url="https://dl.google.com/go/$go_lastest_version.linux-amd64.tar.gz"
    echo "Downloading go version $go_lastest_version from $go_download_url"
    wget $go_download_url -O /tmp/go.tar.gz

    # Remove old version
    if [[ -d "/usr/local/go" ]]; then
        echo "Removing old version of Go"
        sudo rm -rf /usr/local/go
    fi

    # Install new version
    echo "Installing Go version $go_lastest_version"
    sudo tar -C /usr/local -xzf /tmp/go.tar.gz

    # Remove downloaded file
    echo "Removing downloaded tar file"
    rm /tmp/go.tar.gz

    echo "Go version $go_lastest_version installed!"
fi


# Install golang packages
go install go.uber.org/mock/mockgen@latest
go install github.com/air-verse/air@latest
go install github.com/go-delve/delve/cmd/dlv@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
go install github.com/JohannesKaufmann/html-to-markdown/v2/cli/html2markdown@latest