#!/usr/bin/env bash

# Install zsh for macos
if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install zsh
fi

# Install zsh for linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get install zsh
fi


# Add zsh to /etc/shells
if ! grep -q $(which zsh) "/etc/shells"; then
    echo 0
    sudo sh -c "echo $(which zsh) >> /etc/shells"
fi

# Change shell to use zsh
sudo chsh -s $(which zsh)

# Copy configuration files
echo "Copying zsh configuration files to $HOME"
cd shell
cp .zshrc $HOME/.zshrc
cp .aliases $HOME/.aliases
cp .hushlogin $HOME/.hushlogin
cp .path-functions-utils $HOME/.path-functions-utils
cp .zshenv $HOME/.zshenv
cp .zprofile $HOME/.zprofile

# Copy scripts to $HOME/.local/bin
# This is a directory that is added to the PATH in the .zshrc file
# This allows the scripts to be run from the command line globally
echo "Copying scripts to $HOME/.local/bin"
mkdir -p $HOME/.local/bin
cp scripts/* $HOME/.local/bin