- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  become: no
  tags:
    - brew

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  become: no
  tags:
    - brew

- name: Brew bundle
  ansible.builtin.shell: brew bundle --file="~/.dotfiles/Brewfile" --no-lock
  register: brew
  ignore_errors: yes
  become: no
  tags:
    - brew

- name: Brew installation output
  debug: var=brew.stdout_lines
  tags:
    - brew
