# Stow fails if already exist a config file, and needs to use the flag --adopt
# But me need to use our custom config and not the defults
# Thats why before stowing we need to delete some default config files

- name: Remove iterm config file default
  ansible.builtin.file:
    path: ~/Library/Preferences/com.googlecode.iterm2.plist
    state: absent
  tags: 
    - stow
    - iterm

- name: Remove spacelauncher config file default
  ansible.builtin.file:
    path: ~/Library/Preferences/name.guoc.SpaceLauncher.plist
    state: absent
  tags: 
    - stow
    - iterm

- name: Remove gitui theme.ron
  ansible.builtin.file:
    path: ~/.config/gitui/theme.ron
    state: absent
  tags: 
    - stow
    - iterm

- name: Sync .dotfiles with stow
  shell: cd $HOME/.dotfiles && stow -vSt ~ git iterm karabiner qmk raycast vscode zsh scripts tmux gitui nvim alacritty yabai bat spacelauncher
  tags:
    - stow
    - zsh
