---
- name: Install bat
  ansible.builtin.apt:
    name: bat
    state: present
  become: true

- name: Copying bat config
  copy:
    src: config/
    dest: "{{ ansible_user_dir }}/.config/bat"
    mode: 0644
    directory_mode: 0755
    force: true

# TODO: Check if $HOME/.local/bin/bat exists

# Rename package from batcat to bat
# https://github.com/sharkdp/bat?tab=readme-ov-file#on-ubuntu-using-apt
- name: Create a symbolic link (batcat to cat)
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: $HOME/.local/bin/bat
    state: link
