---
# TODO: refactor instead of use script, use ansible build in utility
- name: Install zsh
  community.general.homebrew:
    name: zsh
    state: present

# - name: Set zsh default shell
#   shell: zsh $HOME/.dotfiles/bin/add-zsh-shell
#   become: true

- name: Copying zsh config files
  copy:
    src: "config/"
    dest: "{{ ansible_user_dir }}"
    mode: 0644
    force: true
