---
# TODO: refactor instead of use script, use ansible build in utility
- name: Install zsh
  community.general.homebrew:
    name: zsh
    state: present

- name: Set zsh default shell
  shell: >
    if ! grep -q $(which zsh) "/etc/shells"; then
      echo 0
      sudo sh -c "echo $(which zsh) >> /etc/shells"
    fi

    # Change shell to use zsh
    sudo chsh -s $(which zsh)
  become: true

- name: Copying zsh config files
  copy:
    src: "config/"
    dest: "{{ ansible_user_dir }}"
    mode: 0644
    force: true
