#!/bin/bash

dir=$(find . -type d | grep -v .git | grep -v .vscode | grep -v attachments | fzf --height 40% --reverse --border --prompt "Select a directory: " | head -n 1)

# If no directory is found, exit the scripts
if [ -z "$dir" ]; then
    echo "No directory selected."
    exit 0
fi

# Ask for the file name
read -p "Enter the file name (without extension): " filename

# Check if the file already exists
if [ -f "$dir/$filename.md" ]; then
    echo "File $dir/$filename.md already exists. Opening it in VS Code."
    # If the file exists, open it in VS Code
    code "$dir/$filename.md"

    exit 0
else
    # If the file does not exist, create it and open it in VS Code

    # Define the template content with proper spacing
    template="---\n"
    template+="title: $filename\n"
    template+="date: $(date +\"%Y-%m-%dT%H:%M:%S%z\")\n"
    template+="tags:\n"
    template+="  - \n"
    template+="---\n\n"
    template+="# $filename\n\n"

    # Write the template to the file
    echo -e "$template" > "$dir/$filename.md"

    code "$dir/$filename.md"
fi