---
- name: Tap skhd Homebrew repository
  community.general.homebrew_tap:
    name: koekeishiya/formulae
- name: Install skhd
  community.general.homebrew:
    name: koekeishiya/formulae/skhd
    state: present
- name: Copy skhd configuration file
  copy:
    src: config/.skhdrc
    dest: "{{ ansible_user_dir }}/.skhdrc"
    mode: 0644
    force: true
- name: Launch skhd service
  ansible.builtin.shell: skhd --start-service
