---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true
- name: Copying git config
  copy:
    src: git
    dest: "{{ ansible_user_dir }}"
    mode: 0644
    directory_mode: 0755
    force: true