vscode_extensions:
  - Catppuccin.catppuccin-vsc
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - miguelsolorio.fluent-icons
  - miguelsolorio.symbols
  - streetsidesoftware.code-spell-checker
  - usernamehw.errorlens
  - yoavbls.pretty-ts-errors
  - mhutchie.git-graph
  - vscodevim.vim
  - tobias-z.vscode-harpoon
