---
- name: Install starship
  community.general.homebrew:
    name: starship
    state: present
- name: Copy starship configuration file
  copy:
    src: config/starship.toml
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    mode: 0644
    force: true
