---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
- name: Run macOS Tasks
  ansible.builtin.import_tasks: macos.yml
  when: ansible_os_family == 'Darwin'
- name: Run Window Tasks
  ansible.builtin.import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
