"$schema" = 'https://starship.rs/config-schema.json'

# Starship documentation
# https://starship.rs/config/

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = false

# Starship modules
[character]
success_symbol = "[❯](peach)"
error_symbol = "[✖](bold red)"

# Catppuccin theme https://github.com/catppuccin/starship?tab=readme-ov-file
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[cmd_duration]
min_time = 5_000  # Show command duration over 5,000 milliseconds (=5 sec)
format = " took [$duration]($style)"

[git_metrics]
disabled = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
only_nonzero_diffs=true

[git_status]
disabled = false
# Check icons from Nerd Fonts https://www.nerdfonts.com/cheat-sheet
format = "$ahead$behind$staged$conflict$modified$untracked$stashed "
conflicted = "[󰞇 ${count}](red) "
ahead = "[ ${count}](blue) "
behind = "[ ${count}](blue) "
untracked = "[ ${count}](gray) "
stashed = "[ ${count}](gray) "
modified = "[ ${count}](yellow) "
staged = "[󰾖 ${count}](green) "
renamed = "[󰑕 ${count}](yellow) "
deleted = "[✘ ${count}](red) "

[git_state]
disabled = true
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_branch]
disabled = false
style = "bold mauve"

[git_commit]
disabled = false

[directory]
style = "bold lavender"

[hostname]
disabled = false

[battery]
disabled = true

[package]
disabled = true

[username]
disabled = false