---
- name: Install nvim
  community.general.homebrew:
    name: neovim
    state: present

- name: Create nvim configuration folder
  file: 
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Copy nvim configuration file
  copy:
    src: config/init.lua
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    mode: 0644
    force: true
