---
- name: Download the lsd bundle.
  get_url: url="https://github.com/lsd-rs/lsd/releases/download/v1.1.2/lsd-musl_1.1.2_amd64.deb" dest=/tmp/lsd-musl_1.1.2_amd64.deb

- name: Install lsd package.
  shell: dpkg -i /tmp/lsd-musl_1.1.2_amd64.deb
  become: true
