name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shfmt
        run: echo "TODO"
      - name: Check format with shfmt
        run: echo "TODO format shfmt"
      - name: Install shellcheck
        run: echo "TODO install shellcheck"
      - name: Check linting with shellcheck
        run: echo "TODO lint shellcheck"
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch install and run scripts
        run: ./run
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Launch install and run scripts
        run: ./run