---
- name: Install bat
  community.general.homebrew:
    name: bat
    state: present

- name: Copying config files
  copy:
    src: config/
    dest: "{{ ansible_user_dir }}/.config/bat"
    mode: 0644
    directory_mode: 0755
    force: true
- name: Build bat cache to load themes
  ansible.builtin.shell: bat cache --build
