---
- name: Install bat
  community.general.homebrew:
    name: bat
    state: present

- name: Copying config files
  copy:
    src: bat
    dest: "{{ ansible_user_dir }}/.config"
    mode: 0644
    directory_mode: 0755
    force: true
